services:

  api-biblioteca:
    build: .
    ports:
      - "8080:8000"
    environment: 
      DB_HOST: db-biblioteca 
      DB_PORT: 5432           
      DB_USER: user_biblioteca 
      DB_PASSWORD: password_biblioteca 
      DB_NAME: db_biblioteca 
    depends_on: 
      db-biblioteca:
        condition: service_healthy # Sirve para asegurarnos que la API esta ya disponiblepara que se pueda conectar
    networks:
      - library-net
  
  db-biblioteca: 
    image: postgres:latest
    environment: 
      POSTGRES_USER: user_biblioteca 
      POSTGRES_PASSWORD: password_biblioteca 
      POSTGRES_DB: db_biblioteca 
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - library-net
    healthcheck: # Esto lo he añadido para ver que el servidor de BD de PostgreSQL que puede aceptar conexiones
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"] 
      interval: 5s 
      timeout: 5s  
      retries: 5 
      start_period: 10s

volumes:
  db-data:

networks:
  library-net:
    driver: bridge
