services:

  api-biblioteca:
    build: .
    volumes:
      - library_db:/app/library_app.db
    ports:
      - "8080:8000"
    environment: 
      DB_HOST: db-biblioteca 
      DB_PORT: 5432           
      DB_USER: user_biblioteca 
      DB_PASSWORD: password_biblioteca 
      DB_NAME: db_biblioteca 
    depends_on: 
      - db-biblioteca
    networks:
      - library-net
  
  db-biblioteca: 
    image: postgres:13 
    environment: 
      POSTGRES_USER: user_biblioteca 
      POSTGRES_PASSWORD: password_biblioteca 
      POSTGRES_DB: db_biblioteca 
    volumes:
      - library-db:/var/lib/postgresql/data 
    networks:
      - library-net

volumes:
  library-db:

networks:
  library-net:
    driver: bridge
