services:

  api-biblioteca:
    build: .
    volumes:
      - library_db:/app/library_app.db
    ports:
      - "8080:8000"
    networks:
      - library-net

volumes:
  library_db:

networks:
  library-net:

